// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class appointmentDescriptionOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointmentDescriptionOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201506260644148_appointmentDescriptionOptional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
