// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCCA2Appointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCCA2Appointments));
        
        string IMigrationMetadata.Id
        {
            get { return "201506221310397_AddCCA2Appointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
