// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class notification_status2Appointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notification_status2Appointments));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010822398_notification_status2Appointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
