// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AllowNullIn_notification_statuscolumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AllowNullIn_notification_statuscolumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201507010913404_AllowNullIn_notification_statuscolumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
