// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class doclocations_index_and_user_type_non_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doclocations_index_and_user_type_non_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201507161025396_doclocations_index_and_user_type_non_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
