// <auto-generated />
namespace MiraiConsultMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class add_url_in_doctorlocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_url_in_doctorlocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201507151150341_add_url_in_doctorlocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
